In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,16],[5,12,7]],columns=['cgpa','resume score','package'])

In [39]:
def initialize_pararmeters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)
    for l in range(1, L):
        
        parameters['w' + str(l)] = np.ones((layer_dims[l-1],layer_dims[1]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
    
    return parameters

In [41]:
initialize_pararmeters([2,2,1])

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b2': array([[0.]])}

In [43]:
def linear_forward(A_prev, w, b):
    z = np.dot(w.T, A_prev) + b
    return z

In [194]:
# Forward prpagation 
def L_layer_forward(X, parameters):
    
    A = X                  #first student 
    L = len(parameters) // 2      #no of layers in the NN 

    for i in range(1, L+1):
        A_prev = A
        w1 = parameters['w' + str(i)]
        b1 = parameters['b' + str(i)]
       # print("A"+str(i-1)+": ",A_prev)
       # print("w"+str(i)+": ",w1)
       # print("b"+str(i)+": ",b1)
       # print("--"*20)

        A = linear_forward(A_prev, w1, b1)
       # print("A"+str(i)+": ", A)
       # print("**"*20)

    return A,A_prev

In [132]:
X = df[['cgpa','resume score']].values[0].reshape(2,1)  #shape(no of features, no of training example)
y = df[['package']].values[0][0]

# Parameter initialization
parameters = initialize_pararmeters([2,2,1])

In [134]:
y

4

In [146]:
y_hat, A1 = L_layer_forward(X,parameters)
y_hat, A1

A0:  [[8]
 [8]]
w1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
w2:  [[0.1 0.1]
 [0.1 0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]
 [0.32]]
****************************************


(array([[0.32],
        [0.32]]),
 array([[1.6],
        [1.6]]))

In [148]:
y_hat = y_hat[0][0]

In [136]:
# Loss for the first student 
(y-0.32)**2

13.5424

In [176]:
update_parameters(parameters,y,y_hat,A1,X)

In [178]:
parameters

{'w1': array([[0.1931736 , 0.1107416 ],
        [0.15576548, 0.10866148]]),
 'b1': array([[0.1837747 ],
        [0.14818669]]),
 'w2': array([[0.182432, 0.1     ],
        [0.147104, 0.1     ]]),
 'b2': array([[0.154464]])}

In [180]:
X = df[['cgpa','resume score']].values[1].reshape(2,1)  #shape(no of features, no of training example)
y = df[['package']].values[1][0]

y_hat, A1 = L_layer_forward(X,parameters)
y_hat, A1

A0:  [[7]
 [9]]
w1:  [[0.1931736  0.1107416 ]
 [0.15576548 0.10866148]]
b1:  [[0.1837747 ]
 [0.14818669]]
----------------------------------------
A1:  [[2.93787922]
 [1.90133121]]
****************************************
A1:  [[2.93787922]
 [1.90133121]]
w2:  [[0.182432 0.1     ]
 [0.147104 0.1     ]]
b2:  [[0.154464]]
----------------------------------------
A2:  [[0.97012061]
 [0.63838504]]
****************************************


(array([[0.97012061],
        [0.63838504]]),
 array([[2.93787922],
        [1.90133121]]))

In [186]:
y_hat = y_hat[0][0]

In [188]:
update_parameters(parameters,y,y_hat,A1,X)

In [190]:
parameters

{'w1': array([[0.21773901, 0.11495082],
        [0.1715922 , 0.11178219]]),
 'b1': array([[0.2077718],
        [0.1637374]]),
 'w2': array([[0.2061106 , 0.1       ],
        [0.16242827, 0.1       ]]),
 'b2': array([[0.17048803]])}

In [208]:
# updates weights and biases

def update_parameters(parameters,y,y_hat,A1,X):
    parameters['w2'][0][0] = parameters['w2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
    parameters['w2'][1][0] = parameters['w2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
    parameters['b2'][0][0] = parameters['w2'][1][0] + (0.001 * 2 * (y - y_hat))

    parameters['w1'][0][0] = parameters['w2'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][0][0]*X[0][0])
    parameters['w1'][0][1] = parameters['w2'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['w2'][0][0]*X[1][0])
    parameters['b1'][0][0] = parameters['w2'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][0][0])

    parameters['w1'][1][0] = parameters['w2'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][1][0]*X[0][0])
    parameters['w1'][1][1] = parameters['w2'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['w2'][1][0]*X[1][0])
    parameters['b1'][1][0] = parameters['w2'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][1][0])  

In [210]:
# epoches implimentation

parameters = initialize_pararmeters([2,2,1])
epochs = 10

for i in range(epochs):

    loss = []

    for j in range(df.shape[0]):

        X = df[['cgpa','resume score']].values[j].reshape(2,1)  #shape(no of features, no of training example)
        y = df[['package']].values[j][0]

        # initalize parameters

        y_hat, A1 = L_layer_forward(X,parameters)
        y_hat = y_hat[0][0]

        update_parameters(parameters,y,y_hat,A1,X)

        loss.append((y-y_hat)**2)

    print("Epochs - ",i+1, "loss - ",np.array(loss).mean())
parameters

Epochs -  1 loss -  74.41338209565444
Epochs -  2 loss -  53.937065077846746
Epochs -  3 loss -  36.017959241951736
Epochs -  4 loss -  31.136378610027656
Epochs -  5 loss -  30.74807926440739
Epochs -  6 loss -  30.80103176109458
Epochs -  7 loss -  30.837564525055722
Epochs -  8 loss -  30.853869581341318
Epochs -  9 loss -  30.862787390917244
Epochs -  10 loss -  30.869510742271466


{'w1': array([[0.70455359, 0.04173482],
        [0.35364637, 0.07075415]]),
 'b1': array([[0.72397532],
        [0.36339499]]),
 'w2': array([[0.72883075, 0.1       ],
        [0.36583215, 0.1       ]]),
 'b2': array([[0.3591702]])}